# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krangler/protos/depot_downloader.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&krangler/protos/depot_downloader.proto\x12\x10\x64\x65pot_downloader\x1a\x1fgoogle/protobuf/timestamp.proto\"t\n\tChunkData\x12\x0f\n\x07\x43hunkID\x18\x01 \x01(\x0c\x12\x10\n\x08\x43hecksum\x18\x02 \x01(\x0c\x12\x0e\n\x06Offset\x18\x04 \x01(\x04\x12\x18\n\x10\x43ompressedLength\x18\x05 \x01(\r\x12\x1a\n\x12UncompressedLength\x18\x06 \x01(\r\"\x9f\x01\n\x08\x46ileData\x12\x10\n\x08\x46ileName\x18\x01 \x01(\t\x12+\n\x06\x43hunks\x18\x02 \x03(\x0b\x32\x1b.depot_downloader.ChunkData\x12/\n\x05\x46lags\x18\x03 \x01(\x0e\x32 .depot_downloader.EDepotFileFlag\x12\x11\n\tTotalSize\x18\x04 \x01(\x04\x12\x10\n\x08\x46ileHash\x18\x05 \x01(\x0c\"x\n\rProtoManifest\x12)\n\x05\x46iles\x18\x01 \x03(\x0b\x32\x1a.depot_downloader.FileData\x12\n\n\x02ID\x18\x02 \x01(\x04\x12\x30\n\x0c\x43reationTime\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xab\x01\n\x10\x44\x65potConfigStore\x12Z\n\x14InstalledManifestIDs\x18\x01 \x03(\x0b\x32<.depot_downloader.DepotConfigStore.InstalledManifestIDsEntry\x1a;\n\x19InstalledManifestIDsEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\x04:\x02\x38\x01*\xc4\x01\n\x0e\x45\x44\x65potFileFlag\x12\x08\n\x04None\x10\x00\x12\x0e\n\nUserConfig\x10\x01\x12\x17\n\x13VersionedUserConfig\x10\x02\x12\r\n\tEncrypted\x10\x04\x12\x0c\n\x08ReadOnly\x10\x08\x12\n\n\x06Hidden\x10\x10\x12\x0e\n\nExecutable\x10 \x12\r\n\tDirectory\x10@\x12\x15\n\x10\x43ustomExecutable\x10\x80\x01\x12\x12\n\rInstallScript\x10\x80\x02\x12\x0c\n\x07Symlink\x10\x80\x04')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krangler.protos.depot_downloader_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DEPOTCONFIGSTORE_INSTALLEDMANIFESTIDSENTRY']._options = None
  _globals['_DEPOTCONFIGSTORE_INSTALLEDMANIFESTIDSENTRY']._serialized_options = b'8\001'
  _globals['_EDEPOTFILEFLAG']._serialized_start=670
  _globals['_EDEPOTFILEFLAG']._serialized_end=866
  _globals['_CHUNKDATA']._serialized_start=93
  _globals['_CHUNKDATA']._serialized_end=209
  _globals['_FILEDATA']._serialized_start=212
  _globals['_FILEDATA']._serialized_end=371
  _globals['_PROTOMANIFEST']._serialized_start=373
  _globals['_PROTOMANIFEST']._serialized_end=493
  _globals['_DEPOTCONFIGSTORE']._serialized_start=496
  _globals['_DEPOTCONFIGSTORE']._serialized_end=667
  _globals['_DEPOTCONFIGSTORE_INSTALLEDMANIFESTIDSENTRY']._serialized_start=608
  _globals['_DEPOTCONFIGSTORE_INSTALLEDMANIFESTIDSENTRY']._serialized_end=667
# @@protoc_insertion_point(module_scope)
